# This is a basic workflow to help you get started with Actions

name: deploy Storybook on github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          token: ${{secrets.GITHUB_TOKEN}}
      
#       - name: Merge master -> gh-pages
#         uses: devmasx/merge-branch@v1.3.1
#         with:
#           type: now
#           from_branch: master
#           target_branch: gh-pages
#           github_token: ${{secrets.GITHUB_TOKEN}}

      - name: git merge master
        run: git merge -Xtheirs master
      
      - name: yarn install
        run: yarn install
        
      - name: build core
        run: npm run build:core
      
      - name: build storybook and move to project root
        run : cd ./packages/sketchbox-react;npm run build-storybook;dir;mv ./storybook-static ../../../docs
        
      - name: delete all files except docs
        run : mv ./.git ../.git;sudo rm -rf *
        
      - name: move docs and .git
        run : mv ../docs ./docs;mv ../.git ./.git;dir -a
        
      - name: commit and push
        uses: EndBug/add-and-commit@v7
        with:
          branch: gh-pages
          default_author: github_actions
          message: deploy storybook to github pages
          push: true
          
